version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    command: npm run start
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000